version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mercury-pipeline-metaapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17x4tdwwosg40"
s3_prefix = "mercury-pipeline-metaapi"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
image_repositories = ["Pipeline=008739416430.dkr.ecr.eu-west-2.amazonaws.com/mercurypipelinemetaapi1b4ce271/pipelineaeaeaec5repo"]
parameter_overrides = "ProjectName=\"mercury\" Datalake=\"datalake.dgriffiths.io\" MetaAPIKey=\"arn:aws:secretsmanager:eu-west-2:008739416430:secret:metaapi-key-63qzoR\" MetaAPIDemoAccountID=\"arn:aws:secretsmanager:eu-west-2:008739416430:secret:metaapi-account-id-demo-mJYsCi\""
